import assert from 'node:assert/strict';
import {boothContact,boothChannels,sendBoothInvitation,boothPhotoRoutes} from '../supabase/functions/gallery-api/booth-photos.mjs';
assert.equal(boothContact(null),null);assert.deepEqual(boothContact({channel:'email',recipient:' Guest@Example.test ',consent:true}),{channel:'email',recipient:'guest@example.test',consent:true});assert.equal(boothContact({channel:'sms',recipient:'+1 (555) 555-5555',consent:true}).recipient,'+15555555555');
for(const contact of [{channel:'email',recipient:'x',consent:true},{channel:'sms',recipient:'5555555555',consent:true},{channel:'email',recipient:'a@b.test',consent:false},{channel:'push',recipient:'x',consent:true}])assert.throws(()=>boothContact(contact));
const config={enabled:true,emailKey:'test',smsAccount:'ACtest',smsKey:'secret',smsService:'MGtest'};assert.deepEqual(boothChannels({...config,enabled:false}),[]);
const delivery={id:'delivery',link_token:'a'.repeat(64),recipient:'guest@example.test'};
function service(state='send',save=true){let update;return {rpc:async()=>({data:{status:state,delivery}}),from:()=>({update:v=>{update=v;const q={eq:()=>q,select:()=>q,maybeSingle:async()=>({data:save?{id:'delivery'}:null})};return q;}}),get update(){return update;}};}
const contact={channel:'email',recipient:delivery.recipient,consent:true};
for(const state of ['accepted','busy','cooldown','review','limited']){let calls=0;const result=await sendBoothInvitation(service(state),'hash','request',contact,config,async()=>{calls++;});assert.equal(calls,0);assert.equal(result.status,state);}
let captured;const emailService=service();assert.equal((await sendBoothInvitation(emailService,'hash','request',contact,config,async(url,opts)=>{captured={url,opts};return Response.json({id:'email-1'});})).status,'accepted');assert.equal(captured.opts.headers['Idempotency-Key'],'booth-photo/delivery');assert.match(JSON.parse(captured.opts.body).text,/#booth=/);assert.equal(emailService.update.provider_id,'email-1');
for(const response of [()=>new Response('',{status:503}),()=>{throw Error('offline');},()=>Response.json({})]){const s=service();const result=await sendBoothInvitation(s,'hash','request',{...contact,channel:'sms'},config,response);assert.equal(result.status,'uncertain');assert.equal(s.update.status,'uncertain');assert.ok(!JSON.stringify(result).includes('guest@'));}
assert.equal((await sendBoothInvitation(service(),'h','r',contact,{...config,enabled:false},()=>{throw Error('must not send');})).status,'unconfigured');assert.equal((await sendBoothInvitation(service('send',false),'h','r',contact,config,async()=>Response.json({id:'accepted'}))).status,'uncertain');
const photo={id:'00000000-0000-4000-8000-000000000003',eventId:'event',eventName:'Booth',filename:'image.jpg',expiresAt:'date',preview_key:'event/00000000-0000-4000-8000-000000000003/preview.jpg',preview_bytes:5};
let reads=0,lookups=0,revoked=false,active=true;const s={rpc:async()=>({data:revoked&&++lookups>1?[]:[photo]}),storage:{from:()=>({download:async()=>{reads++;return {data:new Blob(['image'])};}})}};
const client={rpc:async()=>({data:active})},reply=(body,status=200)=>({body,status}),req=new Request('https://local/');
const list=await boothPhotoRoutes(req,['customer','booth','photos'],client,s,{id:'user'},reply,{},null);assert.equal(list.body.photos[0].preview_key,undefined);assert.equal(reads,0);
const parts=['customer','booth','photos',photo.id,'preview'];assert.equal((await boothPhotoRoutes(req,parts,client,s,{id:'user'},reply,{},null)).headers.get('Cache-Control'),'private, no-store');revoked=true;lookups=0;assert.equal((await boothPhotoRoutes(req,parts,client,s,{id:'user'},reply,{},null)).status,404);revoked=false;active=false;assert.equal((await boothPhotoRoutes(req,parts,client,s,{id:'user'},reply,{},null)).status,401);
console.log('PASS: consent/contact validation, feature gating, stable email key, send-state suppression, ambiguous SMS, receipt failure, no PII response, private photo listing and access revalidation.');
// Exercise the real handler guard before privileged photo RPCs.
const {build}=await import('esbuild');
const {outputFiles}=await build({stdin:{contents:"export {storefrontHandler} from './supabase/functions/gallery-api/handler.mts';export {runtime} from './supabase/functions/gallery-api/runtime.mts';",resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'offline',setup(b){b.onResolve({filter:/^@supabase\/supabase-js$/},()=>({path:'auth',namespace:'offline'}));b.onResolve({filter:/server-preview\.mts$/},()=>({path:'image',namespace:'offline'}));b.onLoad({filter:/.*/,namespace:'offline'},a=>({contents:a.path==='auth'?"export function createClient(){throw Error('No live client');}":"export function makeServerPreview(){throw Error('No image processing');}"}));}}]});
const {storefrontHandler,runtime}=await import('data:text/javascript;base64,'+Buffer.from(outputFiles[0].text).toString('base64'));runtime.url='https://test.invalid';runtime.key='public';
globalThis.Deno={env:{get:key=>key==='SUPABASE_SERVICE_ROLE_KEY'?'service':undefined}};
for(const state of [{authorized:false},{authorized:true,user:false},{authorized:true,user:true,active:false},{authorized:true,user:true,active:true,owner:true},{authorized:true,user:true,active:true,owner:false}]){
 let grants=0;const factory=(_url,key)=>key==='service'?{rpc:async()=>{grants++;return {data:[]};}}:{auth:{getUser:async()=>({data:{user:state.user?{id:'verified-user'}:null}})},rpc:async()=>({data:state.active}),from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:state.owner?{user_id:'verified-user',mfa_required:true}:null})})};
 const response=await storefrontHandler(new Request('https://test.invalid/gallery-api/customer/booth/photos',{headers:{Origin:'https://www.atelierelunora.com','X-Elunora-Request':'1',...(state.authorized?{Authorization:'Bearer aal1'}:{})}}),factory);
 assert.equal(response.status,state.owner?403:state.authorized&&state.user&&state.active?200:401);assert.equal(grants,response.status===200?1:0);
}
console.log('PASS: real HTTP handler blocks missing/invalid/revoked sessions and owners without MFA before creating privileged photo grants.');
