import assert from 'node:assert/strict';
import {invitationEmail,sendInvitationEmail} from '../supabase/functions/gallery-api/invitation-email.mjs';
import {laterEmail} from '../supabase/functions/gallery-api/later-email.mjs';
const event={id:'11111111-1111-4111-8111-111111111111',name:'Alex & <Breanna>',active:true,deleted_at:null};const email='couple@example.test',expires=new Date(Date.now()+86400000).toISOString();
const template=invitationEmail(event,email,expires),brand=laterEmail({order_name:'#test',expires_at:expires},'https://www.atelierelunora.com');
assert.equal(template.from,brand.from);assert.equal(template.reply_to,brand.reply_to);assert.deepEqual(template.to,[email]);assert.match(template.html,/Alex &amp; &lt;Breanna&gt;/);assert.ok(!template.html.includes('<Breanna>'));assert.match(template.html,/Create or reset password/);assert.match(template.text,/email code/);assert.match(template.html,/lang="en"/);assert.match(template.html,/role="presentation"/);assert.match(template.html,/Open your gallery/);assert.ok(!template.html.includes('preview_theme_id'));
for(const color of ['#4A4B36','#E8E5D9','#F8F7F3'])assert.ok(template.html.includes(color)&&brand.html.includes(color));assert.equal(template.html.match(/<img src="([^"]+)/)[1],brand.html.match(/<img src="([^"]+)/)[1]);
let requests=[],writes=[],rpcCalls=[],state;function reset(overrides={}){requests=[];writes=[];rpcCalls=[];state={event,invite:{email,expires_at:expires,revoked:false},prepared:{status:'send',delivery:{version:'message-id',payload:template}},...overrides};}
const service={rpc:async(name,args)=>{rpcCalls.push({name,args});return {data:state.prepared,error:state.prepareError};},from(table){let update;return {select(){return this;},eq(){return this;},update(value){update=value;writes.push(value);return this;},maybeSingle:async()=>update?{data:state.saveError?null:{status:update.status},error:state.saveError}:table==='gallery_events'?{data:state.event}:{data:state.invite}};}};
async function fetcher(url,options){requests.push({url,options});if(state.networkError)throw Error('timeout');return {ok:!state.httpError,status:state.httpError||200,json:async()=>({id:'provider-id'})};}
const send=(resend=false,key='server-key')=>sendInvitationEmail(service,event.id,email,{key,fetcher},resend);
reset();let r=await send();assert.equal(r.status,'accepted');assert.equal(requests[0].options.headers['Idempotency-Key'],'gallery-invitation/message-id');assert.deepEqual(JSON.parse(requests[0].options.body),template);assert.equal(writes[0].provider_id,'provider-id');assert.equal(rpcCalls[0].args.p_resend,false);
reset();await send(true);assert.equal(rpcCalls[0].args.p_resend,true);
reset();assert.equal((await send(false,'')).status,'unconfigured');assert.equal(requests.length,0);
for(const overrides of [{event:{...event,active:false}},{event:{...event,deleted_at:expires}},{invite:null},{invite:{email,expires_at:expires,revoked:true}},{invite:{email,expires_at:'2020-01-01',revoked:false}}]){reset(overrides);assert.equal((await send()).status,'unavailable');assert.equal(requests.length,0);assert.equal(rpcCalls.length,0);}
for(const status of ['already_accepted','busy','cooldown','limited','review','changed']){reset({prepared:{status}});assert.equal((await send()).status,status);assert.equal(requests.length,0);}
for(const [overrides,status] of [[{httpError:422},'failed'],[{httpError:429},'failed'],[{httpError:500},'uncertain'],[{httpError:409},'uncertain'],[{networkError:true},'uncertain'],[{saveError:{}},'uncertain']]){reset(overrides);assert.equal((await send()).status,status);assert.ok(!JSON.stringify(await send()).includes('server-key'));assert.equal(requests.at(-1).options.headers['Idempotency-Key'],'gallery-invitation/message-id');}
console.log('PASS: existing email branding, escaped content and private canonical link; eligibility, provider receipt, failures, ambiguous sends, idempotency and safe recipient construction. No emails sent.');
