import {build} from 'esbuild';import assert from 'node:assert/strict';import {Window} from 'happy-dom';
const {outputFiles}=await build({stdin:{contents:`import {h,render} from 'preact';import {Access} from './dashboard/Access.jsx';import {installNativeControls} from './dashboard/ui.jsx';installNativeControls();window.mount=props=>render(h(Access,props),document.body);`,resolveDir:process.cwd()+'/shopify-owner-app',loader:'jsx'},bundle:true,format:'iife',write:false,jsxFactory:'h',jsxFragment:'Fragment'});
const pause=()=>new Promise(r=>setTimeout(r,20));
const w=new Window({url:'https://www.atelierelunora.com/pages/owner-studio?preview_theme_id=123'});w.eval(outputFiles[0].text);
const calls=[],errors=[];let emailStatus='uncertain';const detail={event:{id:'event',name:'Couple celebration',active:true},invitations:[],grants:[],invitationEmails:[]};
const props={detail,galleryUrl:'/pages/client-gallery?preview_theme_id=123',busy:false,run:async f=>{try{await f();}catch(e){errors.push(e.message);}},reload:async()=>{},call:async(path,body)=>{calls.push({path,body});if(path.endsWith('/access')){detail.invitations=[{email:body.email,expires_at:body.expiresAt,revoked:false}];detail.invitationEmails=[{email:body.email,status:emailStatus,accepted_at:emailStatus==='accepted'?new Date().toISOString():null}];}return {saved:true,email:{status:emailStatus,message:emailStatus==='accepted'?'Invitation email accepted for sending.':'Access is saved, but email acceptance could not be confirmed.'}};}};
w.mount(props);await pause();const button=text=>{const b=[...w.document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);return b;};
async function type(sel,value){const n=w.document.querySelector(sel);n.value=value;n.dispatchEvent(new w.Event('input',{bubbles:true}));await pause();}
assert.equal(w.document.querySelector('input[type=checkbox]').checked,true);await type('input[type=email]','couple@example.test');await type('input[type=date]','2099-12-01');w.document.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();assert.equal(calls[0].body.sendEmail,true);assert.match(w.document.body.textContent,/Access is saved, but email acceptance/);assert.ok(button('Retry invitation email'));
emailStatus='accepted';button('Retry invitation email').click();await pause();assert.ok(calls.at(-1).path.endsWith('/invitation-email'));assert.match(w.document.body.textContent,/accepted for sending/);
const toggle=w.document.querySelector('input[type=checkbox]');toggle.checked=false;toggle.dispatchEvent(new w.Event('change',{bubbles:true}));await pause();assert.ok(button('Save guest access'));await type('input[type=email]','other@example.test');await type('input[type=date]','2099-12-02');w.document.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();assert.equal(calls.at(-1).body.sendEmail,false);
detail.event.active=false;w.mount({...props,detail:{...detail}});await pause();const t=w.document.querySelector('input[type=checkbox]');t.checked=true;t.dispatchEvent(new w.Event('change',{bubbles:true}));await pause();assert.equal(button('Save access and send invitation').disabled,true);assert.deepEqual(errors,[]);await w.happyDOM.abort();
console.log('PASS: automatic sending defaults on, failed email leaves saved access with retry, resend feedback, optional save-only and paused-gallery send prevention.');
