import assert from 'node:assert/strict';
import {stationOriginAllowed} from '../supabase/functions/gallery-api/station-origin.mjs';
import {stationRequest} from '../supabase/functions/gallery-api/station.mjs';
const make=(path='station',method='POST',extra={})=>new Request('https://example.supabase.co/functions/v1/gallery-api/'+path,{method,headers:{'X-Elunora-Request':'1',...extra}});
assert.equal(stationOriginAllowed(make()),false,'native clients disabled by default');
assert.equal(stationOriginAllowed(make(),true),true);
for(const origin of ['null','','https://evil.example']) assert.equal(stationOriginAllowed(make('station','POST',{Origin:origin}),true),false);
for(const path of ['owner/events','login','session','station/','station/x']) assert.equal(stationOriginAllowed(make(path),true),false);
for(const method of ['GET','OPTIONS','DELETE']) assert.equal(stationOriginAllowed(make('station',method),true),false);
assert.equal(stationOriginAllowed(new Request('https://example.supabase.co/functions/v1/gallery-api/station',{method:'POST'}),true),false);
assert.equal(stationOriginAllowed(make('owner/events','POST',{Origin:'https://www.atelierelunora.com'})),true);
const reply=(body,status=200)=>({body,status});
let checks=0;
const denied={rpc:async()=>{checks++;return {error:{code:'PT403'}};}};
assert.equal((await stationRequest({purpose:'capture',action:'info'},denied,reply)).status,403);
assert.equal(checks,0);
assert.equal((await stationRequest({token:'a'.repeat(64),purpose:'capture',action:'info'},denied,reply)).status,403);
assert.equal(checks,1,'syntactically valid native token still requires database authorization');
console.log('PASS: native opt-in, route/method/header restrictions, cross-origin rejection, and token authorization.');

assert.equal(stationOriginAllowed(new Request('https://internal/gallery-api/station',{method:'POST',headers:{'X-Elunora-Request':'1'}}),true),true,'Supabase internal path');
assert.equal(stationOriginAllowed(new Request('https://internal/gallery-api/owner',{method:'POST',headers:{'X-Elunora-Request':'1'}}),true),false);
