import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {advance} from '../print-helper/engine.mjs';
import {parseStatus,statusRequest} from '../print-helper/cups.mjs';
import {renderSheets,calibrationSheet} from '../print-helper/render.mjs';
import {createCanvas} from '../print-helper/node_modules/@napi-rs/canvas/index.js';
import {createRequire} from 'node:module';
const {PDFDocument}=createRequire(new URL('../print-helper/main.mjs',import.meta.url))('pdf-lib');
const bytes=Buffer.from('print'),base={id:'test',state:'prepared',file:'test.pdf',sha256:createHash('sha256').update(bytes).digest('hex')};
let saved=null,submissions=0,completions=0,archives=0,state=5;
const deps={journal:{write:async j=>{saved=j;},archive:async()=>{archives++;}},read:async()=>bytes,authorize:async()=>{},submit:async()=>{submissions++;return 'DNP-123';},status:async()=>state,complete:async()=>{completions++;}};
await advance(base,deps);assert.equal(saved.state,'submitted');assert.equal(submissions,1);await advance(saved,deps);assert.equal(submissions,1);state=9;await advance(saved,deps);assert.equal(completions,1);assert.equal(archives,1);
await assert.rejects(advance({...base,state:'submitting'},deps),/uncertain/);assert.equal(submissions,1);
await assert.rejects(advance(base,{...deps,submit:async()=>{throw Error('lost acknowledgement');}}),/lost acknowledgement/);assert.equal(saved.state,'submitting');
await assert.rejects(advance(base,{...deps,authorize:async()=>{throw Error('refund');}}),/refund/);assert.equal(submissions,1);
await assert.rejects(advance({...base,state:'submitted',spoolerJob:'DNP-123'},{...deps,status:async()=>7}),/needs attention/);
let attempts=0;await assert.rejects(advance({...base,state:'submitted',spoolerJob:'DNP-123'},{...deps,status:async()=>9,complete:async()=>{attempts++;throw Error('offline');}}),/offline/);assert.equal(saved.state,'computer-completed');await advance(saved,{...deps,complete:async()=>{attempts++;}});assert.equal(attempts,2);assert.equal(submissions,1);
assert.equal(statusRequest(123).readUInt16BE(2),9);
const attr=(name,n)=>{const key=Buffer.from(name),b=Buffer.alloc(9+key.length);b[0]=0x23;b.writeUInt16BE(key.length,1);key.copy(b,3);b.writeUInt16BE(4,key.length+3);b.writeInt32BE(n,key.length+5);return b;};
const response=Buffer.concat([Buffer.from([1,1,0,0,0,0,0,1,2]),attr('job-id',123),attr('job-state',9),Buffer.from([3])]);assert.equal(parseStatus(response,123),9);assert.throws(()=>parseStatus(response,124));assert.throws(()=>parseStatus(Buffer.from([1]),123));
const image=createCanvas(100,100);image.getContext('2d').fillRect(0,0,100,100);const pdf=await renderSheets([{id:'photo',quantity:6,x:50,y:50,zoom:1,template:{enabled:false,photoCutInches:3.75}}],new Map([['photo',image.toBuffer('image/png')]]),'Test',null);
const doc=await PDFDocument.load(pdf);assert.equal(doc.getPageCount(),1);assert.equal(doc.getPage(0).getWidth(),576);assert.equal(doc.getPage(0).getHeight(),864);assert.equal((await PDFDocument.load(await calibrationSheet())).getPageCount(),1);
console.log('PASS: durable submission boundary, no retry on uncertainty, refund recheck, completed-job acknowledgement retries, exact CUPS job identity and 8 × 12 PDF rendering.');
