import {h,Fragment} from 'preact';
import {useEffect,useState} from 'preact/hooks';
export function AutomaticPrinting({event,call,run,busy,demo}){
 const simulation=demo&&location.hostname==='127.0.0.1'&&new URLSearchParams(location.search).get('simulation')==='1';
 const request=simulation?async(_route,body)=>{const res=await fetch('/simulation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error);return data;}:call;
 const [data,setData]=useState(null),[error,setError]=useState(''),[code,setCode]=useState(null),[resolve,setResolve]=useState(null),[reprint,setReprint]=useState(null),[reason,setReason]=useState('');
 const route='owner/automatic/'+event.id;
 async function load(){if(demo&&!simulation){setData({helpers:[],runs:[],waiting:{jobs:0,copies:0,uniquePhotos:0}});return;}try{setData(await request(route,{action:'status'}));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();const timer=setInterval(load,simulation?1000:3000);return()=>clearInterval(timer);},[event.id]);
 async function action(action,helperId,extra={}){await request(route,{action,helperId,...extra});if(action==='revoke'&&code?.helperId===helperId)setCode(null);await load();}
 return <details class="panel" open><summary>Hands-free printing · {simulation?'Simulation':'Print helper'}</summary>
 {simulation&&<div><p><strong>SIMULATION ONLY.</strong> Sample queue, no customer data and no physical printing. Starts with 13 copies. The six-slot layout is provisional until a printer is selected.</p><button onClick={()=>run(()=>action('add',null,{count:6}))}>Add 6 sample photos</button><button onClick={()=>run(()=>action('add',null,{count:1}))}>Add 1 sample photo</button><button onClick={()=>run(()=>action('fault-next'))}>Simulate lost printer response</button></div>}
 <section aria-label="Launch print helper"><h3>Open your printer connection</h3><p>On the printer-connected Windows computer or Mac, use the button below after the one-time setup. Your browser may ask permission to open Atelier Print Helper. Launching does not start printing.</p><a class="primary" href="atelier-print://open">Launch Print Helper</a><p><a href="http://127.0.0.1:4318" target="_blank" rel="noopener noreferrer">Helper already running? Open printer settings</a></p><details><summary>First-time setup or button not opening?</summary><p>Extract the latest helper ZIP into a permanent folder. Close any older helper. Run Enable Dashboard Launch.cmd on Windows, or Enable Dashboard Launch.command on Mac. Node.js 22 or newer is required. Keep the folder in place; rerun setup if you move it. Mac setup is awaiting a physical Mac test.</p><p>Once it opens, pair this event and verify the saved printer. Use Start automatic printing here when ready. Printer selection and calibration open in the local helper window; event controls and sheet confirmations stay in this dashboard.</p></details></section>
 <p>Connect the printer to your Windows computer or Mac and start the Atelier Print Helper there. Pair this event, select the installed printer in the helper, then print and inspect a test sheet. Keep that computer awake. The manual print desk remains available below.</p>
 <details><summary>Connect a real printer</summary><ol><li>On the printer-connected computer, install the printer driver and launch Atelier Print Helper.</li><li><a href="http://127.0.0.1:4318" target="_blank" rel="noopener noreferrer">Open the local Print Helper</a>. This address only works on that computer while the helper is running.</li><li>In the live dashboard, generate a pairing code and paste it into the helper. Preview codes only connect the simulator.</li><li>Select the printer and supported paper size, save, and print one calibration sheet.</li><li>Confirm the measurements and job monitoring, then connect the validated printer. Native automatic printing also requires server activation after hardware acceptance.</li></ol><p>Supported layouts: four magnets on Letter, or six on 8 × 12. Select the paper that matches your printer. The helper is currently a source release, not an installed app.</p></details>
 {error&&<p role="alert">{error}</p>}
 {data&&<><p>{data.waiting.jobs} waiting photo jobs · {data.waiting.copies} magnet copies · {data.waiting.uniquePhotos} unique photos</p>
 <button disabled={busy||(demo&&!simulation)} onClick={()=>run(async()=>{setCode(await request(route,{action:'pair'}));await load();})}>Pair a print helper</button>
 {code&&<div><label>Single-use pairing code<input readOnly type="text" value={code.code}/></label><p>{simulation?'Use the button below to simulate entering this code in the helper.':'Paste into the local helper within five minutes.'} Pairing does not start printing. Code expires at {new Date(code.expiresAt).toLocaleTimeString()}.</p>{simulation&&<button disabled={busy} onClick={()=>run(async()=>{await action('connect',code.helperId,{code:code.code});setCode(null);})}>Connect simulated helper</button>}</div>}
 {data.helpers.filter(helper=>data.runs.some(r=>r.helper_id===helper.id&&r.state==='active')||!(helper.mode==='ended'||helper.gallery_stations?.revoked||(helper.gallery_stations?.expires_at&&Date.parse(helper.gallery_stations.expires_at)<=Date.now()))).map(helper=>{const active=data.runs.find(r=>r.helper_id===helper.id&&r.state==='active');const stale=!helper.heartbeat_at||Date.now()-Date.parse(helper.heartbeat_at)>45000;return <section key={helper.id}><h3>{helper.printer?.printer||'New helper'} · {helper.mode}</h3>
 <p>{helper.paired?(stale?'Disconnected or waiting for heartbeat':'Connected'):'Awaiting pairing'} · {helper.printer?.adapter==='simulation'?'SIMULATED PRINTER — no physical output':helper.printer?'Calibrated printer':'Calibration required'}</p>
 {helper.attention&&<p role="alert">{helper.attention}</p>}
 <button disabled={busy||stale||!helper.paired||!helper.printer} onClick={()=>run(()=>action('start',helper.id))}>Start automatic printing</button>
 <button disabled={busy} onClick={()=>run(()=>action('pause',helper.id))}>Pause</button>
 <button disabled={busy||helper.mode!=='running'} onClick={()=>run(()=>action('flush',helper.id))}>Print waiting photos now</button>
 <button disabled={busy} onClick={()=>run(()=>action('end',helper.id))}>Finish one run & stop (up to 200 copies)</button>
 <button disabled={busy} onClick={()=>run(()=>action('revoke',helper.id))}>Disconnect helper</button>
 <label>Partial sheet delay<select value={helper.partial_seconds} disabled={busy||helper.mode==='running'} onChange={e=>run(()=>action('settings',helper.id,{partialSeconds:Number(e.currentTarget.value)}))}><option value="0">Full sheets only</option><option value="60">1 minute</option><option value="120">2 minutes</option><option value="300">5 minutes</option></select></label>
 {active&&<>{(helper.mode==='ended'||helper.gallery_stations?.revoked)&&<p role="status">This helper is disconnected. Resolve its unfinished sheets below; then it will disappear from this list.</p>}<p>Reserved run: {active.gallery_helper_sheets.filter(s=>['completed','operator'].includes(s.state)).length} of {active.gallery_helper_sheets.length} sheets completed.</p><button disabled={busy} onClick={()=>setResolve({helperId:helper.id,runId:active.id})}>Resolve manually</button></>}
 </section>;})}
 {resolve&&<section><p>Inspect physical output and the computer’s printer queue first. Pause the helper. Confirm completion only after every sheet in this run is physically printed. Releasing is allowed only before any submission attempt.</p><button disabled={busy} onClick={()=>run(async()=>{await action('resolve',resolve.helperId,{runId:resolve.runId,confirm:true,outcome:'printed'});setResolve(null);})}>I verified all sheets printed</button><button disabled={busy} onClick={()=>run(async()=>{await action('resolve',resolve.helperId,{runId:resolve.runId,confirm:true,outcome:'release'});setResolve(null);})}>Return unsubmitted run to manual queue</button><button onClick={()=>setResolve(null)}>Cancel</button></section>}
 {reprint&&<section><h3>Reprint event photos</h3><p>This creates new copies and preserves the original print history.</p>{reprint.items.filter((item,i,all)=>all.findIndex(x=>x.id===item.id)===i).map((item,i)=><label key={i}><input type="checkbox" checked={reprint.selected.includes(item.id)} onChange={e=>setReprint(r=>({...r,selected:e.currentTarget.checked?[...r.selected,item.id]:r.selected.filter(id=>id!==item.id)}))}/>Photo {i+1}</label>)}<label>Reason<input value={reason} onInput={e=>setReason(e.currentTarget.value)} maxLength={200}/></label><button disabled={busy||reason.trim().length<3||!reprint.selected.length} onClick={()=>run(async()=>{await action('reprint',reprint.helperId,{requestId:reprint.requestId,sheetId:reprint.sheetId,reason,jobIds:reprint.selected});setReprint(null);setReason('');})}>Queue selected copies</button><button onClick={()=>setReprint(null)}>Cancel</button></section>}
 <h3>Recent sheets</h3>{data.runs.map(r=><div key={r.id}>{r.gallery_helper_sheets.map(s=><p key={s.id}>Sheet {s.sheet_index+1} · {s.items.length} magnet copies · {({completed:'Completed by computer',operator:'Operator confirmed',attention:'Needs attention',submitted:'Sent to printer',awaiting_confirmation:'Check the printed sheet',submitting:'Submission in progress — do not resend',preparing:'Preparing',released:'Returned to manual queue'})[s.state]}{s.spooler_job?' · '+s.spooler_job:''}{r.state==='active'&&s.state==='awaiting_confirmation'&&<span><br/>Check that all {s.items.length} magnets on sheet {s.sheet_index+1} printed correctly. <button disabled={busy} onClick={()=>run(()=>action('confirm-sheet',r.helper_id,{runId:r.id,sheetId:s.id,spoolerJob:s.spooler_job,confirm:true}))}>Printed successfully—continue</button></span>}{['completed','operator'].includes(r.state)&&['completed','operator'].includes(s.state)&&<button disabled={busy} onClick={()=>{setReason('');setReprint({helperId:r.helper_id,sheetId:s.id,items:s.items,selected:[...new Set(s.items.map(i=>i.id))],requestId:crypto.randomUUID()});}}>Reprint sheet or selected photos</button>}</p>)}</div>)}
 </>}
 </details>;
}
