import {orderContact} from '../extensions/gallery-owner/src/workflows.mjs';
import {h,Fragment} from 'preact';
import {useState} from 'preact/hooks';
import {RequestCard} from '../extensions/gallery-owner/src/shared-owner.jsx';
import {commerceOrders,uploaderLink} from './commerce.mjs';
import {Empty} from './ui.jsx';

export function Commerce({data,commerce,call,run,busy,refresh,open,galleryUrl}){
 const [section,setSection]=useState('orders'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[copied,setCopied]=useState('');
 if(!commerce)return <Empty title="Online store unavailable">Refresh your studio to try again.</Empty>;
 const orders=commerceOrders(data,commerce,{query,filter}),all=commerceOrders(data,commerce),link=uploaderLink(galleryUrl,location.origin,location.search);
 const workspaces=commerce.workspaces.filter(w=>{const e=data.events.find(e=>e.id===w.event_id);return e&&!e.deleted_at&&!e.purge_started_at;});
 return <>
  <section class="commerce-intro panel"><div><p class="eyebrow">FROM THEIR CAMERA TO A KEEPSAKE</p><h2>Your online magnet studio.</h2><p>Customer uploads, saved selections, verified orders and printing in one place.</p></div><span class={'badge '+(commerce.checkoutEnabled?'active':'')}>{commerce.checkoutEnabled?'Checkout enabled':'Checkout paused'}</span></section>
  {!commerce.checkoutEnabled&&<p class="notice">The custom uploader is being prepared for launch. Customers cannot pay through this flow yet. Saved photos and selections remain available.</p>}
  <div class="stats">{[['Online selections',all.length],['Paid, in progress',commerceOrders(data,commerce,{filter:'paid'}).length],['Payment review',commerceOrders(data,commerce,{filter:'review'}).length],['Photo workspaces',workspaces.length]].map(([label,value])=><div class="stat"><p>{label}</p><strong>{value}</strong><small>Current loaded records</small></div>)}</div>
  <div class="tabs" role="navigation" aria-label="Online store"><button aria-current={section==='orders'?'page':undefined} onClick={()=>setSection('orders')}>Online orders</button><button aria-current={section==='customers'?'page':undefined} onClick={()=>setSection('customers')}>Customer photos</button><button aria-current={section==='setup'?'page':undefined} onClick={()=>setSection('setup')}>Uploader & packs</button></div>
  {section==='orders'&&<><div class="order-toolbar"><label class="search">Find an online order<input type="search" placeholder="Email, Shopify order or selection reference…" value={query} onInput={e=>setQuery(e.currentTarget.value)}/></label><label class="field">Payment & preparation<select value={filter} onChange={e=>setFilter(e.currentTarget.value)}>{[['all','All online selections'],['paid','Paid, in progress'],['review','Needs payment review'],['completed','Completed'],['cancelled','Cancelled']].map(([value,label])=><option value={value}>{label}</option>)}</select></label></div><p class="muted">Online selections from the latest 200 selections and payment records. Status changes here do not mark a Shopify order fulfilled.</p><div class="order-list">{orders.map(r=><div key={r.id}><RequestCard request={r} events={data.events} payments={data.payments} call={call} run={run} busy={busy} refresh={refresh}/><button disabled={busy} onClick={()=>run(()=>open(r.event_id,'desk'))}>Open order print desk</button></div>)}</div>{!orders.length&&<Empty title="No matching online orders">Customer selections from the custom uploader will appear here. Event orders remain in Orders.</Empty>}</>}
  {section==='customers'&&<section class="panel"><h2>Private customer photo workspaces</h2><p>Each customer uploads into a private collection. Their checkout email appears after an order is received. Open a collection to inspect uploads or manage production.</p>{workspaces.map(w=>{const event=data.events.find(e=>e.id===w.event_id),requests=all.filter(r=>r.event_id===w.event_id),emails=[...new Set(requests.map(r=>orderContact(r,data.payments)))];return <div class="connection" key={w.event_id}><div><h3>{emails.join(', ')||'Customer has not submitted a selection'}</h3><p>{event.name} · {w.event_id.slice(0,8)}</p><p class="muted">{w.enabled&&event.active&&Date.parse(w.closes_at)>Date.now()?'Upload access open':'Upload access paused or expired'} · {requests.length} loaded selections</p></div><button disabled={busy} onClick={()=>run(()=>open(w.event_id,'photos'))}>Open photos</button></div>;})}{!workspaces.length&&<Empty title="No customer uploads yet">Workspaces appear when customers begin a private upload.</Empty>}{commerce.truncated&&<p role="status">Showing the latest 500 workspaces. Older collections are available in Events.</p>}</section>}
  {section==='setup'&&<><section class="panel"><h2>Branded customer uploader</h2><p>Upload photos → adjust crops and copies → Shopify checkout.</p><label class="field">Customer uploader<input readOnly value={link}/></label><div class="row"><a href={link} target="_blank" rel="noopener noreferrer">Open customer uploader ↗</a><button onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied('Uploader link copied.');}catch{setCopied('Select and copy the link above.');}}}>Copy uploader link</button></div>{copied&&<p role="status">{copied}</p>}<p class="muted">Customer checkout is available for configured magnet packs.</p></section><section class="panel"><h2>Connected magnet packs</h2><p>Configured checkout prices. Shopify availability and price are checked again at checkout; these are not live inventory readings.</p><div class="table-scroll"><table><thead><tr><th>Pack</th><th>Configured price</th><th>Shopify variant</th></tr></thead><tbody>{commerce.packs.map(p=><tr key={p.variant}><td>{p.count} magnets</td><td>{new Intl.NumberFormat(undefined,{style:'currency',currency:commerce.currency}).format(p.cents/100)}</td><td>{p.variant}</td></tr>)}</tbody></table></div><p class="muted">Pack configuration and Shopify pricing must agree before launch. Refunds, shipping and fulfillment remain in Shopify.</p><a href="https://admin.shopify.com/store/v0j63n-ms/orders" target="_blank" rel="noopener noreferrer">Open Shopify orders ↗</a></section></>}
 </>;
}
