import {h} from 'preact';
import {useState} from 'preact/hooks';
const labels={awaiting_photos:'Awaiting photos',submitted:'Photos submitted',queued:'In print queue',completed:'Preparation complete'};
function LaterOrder({order,call,run,busy,refresh,open}){
 const [link,setLink]=useState(''),[message,setMessage]=useState('');
 const action=kind=>run(async()=>{const r=await call('owner/upload-later',{action:kind,id:order.id});if(kind==='link'){setLink(r.url);try{await navigator.clipboard.writeText(r.url);setMessage('Private link copied.');}catch{setMessage('Copy the private link below.');}}else{setMessage(kind==='resend'?'Upload email sent.':kind==='produce'?'Photos added to the print desk.':'Preparation marked complete.');await refresh();}});
 return <article class="panel"><p class="eyebrow">{labels[order.status]}</p><h3>Order {order.order_name}</h3><p>{order.product_title} · {order.required_count} magnets</p><p>{order.email_sent_at?'Upload email sent '+new Date(order.email_sent_at).toLocaleString():'Upload email awaiting delivery'}</p>{order.email_error&&<p role="alert">{order.email_error}</p>}<div class="actions"><button disabled={busy} onClick={()=>run(()=>open(order.event_id))}>Open order photos</button>{order.status==='awaiting_photos'&&<><button disabled={busy} onClick={()=>action('link')}>Copy upload link</button><button disabled={busy} onClick={()=>action('resend')}>Resend upload email</button></>}{order.status==='submitted'&&<button class="primary" disabled={busy} onClick={()=>action('produce')}>Send to print desk</button>}{order.status==='queued'&&<button disabled={busy} onClick={()=>action('complete')}>Mark preparation complete</button>}</div>{link&&<label class="field">Private customer link<input readOnly value={link} onFocus={e=>e.currentTarget.select()}/></label>}{message&&<p role="status">{message}</p>}</article>;
}
export function LaterOrders({orders=[],...props}){
 const active=orders.filter(order=>order.status!=='completed'),completed=orders.filter(order=>order.status==='completed');
 return <section><h2>Upload-later orders</h2><p>Customers receive a private upload link after payment. Orders needing attention appear here.</p>{active.length?<div class="order-list">{active.map(order=><LaterOrder key={order.id} order={order} {...props}/>)}</div>:<p>{completed.length?'All upload-later orders are complete.':'No upload-later orders yet.'}</p>}{completed.length>0&&<details class="panel"><summary>Completed upload-later orders ({completed.length})</summary><div class="order-list">{completed.map(order=><LaterOrder key={order.id} order={order} {...props}/>)}</div></details>}</section>;
}
